# 1. FUERZA LA IMAGEN DE PYTHON
FROM python:3.11-slim

# 2. CONFIGURACIÓN DEL ENTORNO
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. DIRECTORIO DE TRABAJO DENTRO DEL CONTENEDOR
# /app es la carpeta dentro del contenedor.
WORKDIR /app

# 4. INSTALACIÓN DE DEPENDENCIAS (Optimizada)
# Copia requirements.txt (que debe estar en /Backend)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. COPIA DEL CÓDIGO
# Copia todos los archivos restantes de /Backend a /app
COPY . /app

# 6. COMANDO DE EJECUCIÓN
# Comando explícito para ejecutar Alembic y luego Uvicorn (FastAPI)
CMD ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]